---
repo-name: peripherals-ms-project
categories:
- Project Management
- Collaboration
display-name: Microsoft Project
manufacture: Microsoft
product: Project
description: Microsoft Project is a project management software product, developed
  and sold by Microsoft. It is designed to assist a project manager in developing
  a plan, assigning resources to tasks, tracking progress, managing the budget, and
  analyzing workloads.
